## Passengers

POST http://localhost:8050/passengers HTTP/1.1
content-type: application/json

{
    "name": "Inez",
    "flightId": "356a5cfe-9602-4a54-8943-1715477571c3"
}
### 

DELETE http://localhost:8050/passengers HTTP/1.1
content-type: application/json

{
    "id": "1f58f4c6-416b-46cf-9cfd-dbf1c1e4a152"
}

### 
PUT http://localhost:8050/passengers HTTP/1.1
content-type: application/json

{
    "id": "6424cf4e-964e-4ab3-910f-d0d3293549a7",
    "flightId": "356a5cfe-9602-4a54-8943-1715477571c3",
    "name": "ALLAN",
    "status": 1
}

### 
GET http://localhost:8050/passengers/5563782b-34c9-4397-bf37-d6d27019dc62 HTTP/1.1

###
GET http://localhost:8050/passengers/flight/356a5cfe-9602-4a54-8943-1715477571c3 HTTP/1.1



### Flights
POST http://localhost:80/flights HTTP/1.1
content-type: application/json

{
    "destination": "Malmö",
    "origin": "Kuala Lumpur",
    "flightNumber": "KL123"
}

### 
DELETE http://localhost:80/flights HTTP/1.1
content-type: application/json

{
    "id": "8ee3e7dc-8c15-4c0a-9834-226ab1545aea"
}

###
PUT http://localhost:80/flights HTTP/1.1
content-type: application/json

{
    "destination": "Dallas",
    "origin": "Kuala Lumpur",
    "flightNumber": "KL123",
    "id": "356a5cfe-9602-4a54-8943-1715477571c3",
    "status": 2
}

###
GET http://localhost:80/flights/356a5cfe-9602-4a54-8943-1715477571c3 HTTP/1.1

###
GET http://localhost:80/flights HTTP/1.1

